services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.29.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pygeoapi

  pygeoapi:
    image: geopython/pygeoapi:0.22.0
    volumes:
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro
      - ./pygeoapi/ne_110m_lakes.geojson:/pygeoapi/ne_110m_lakes.geojson:ro
    environment:
      - SCRIPT_NAME=/pygeoapi
    deploy:
      replicas: 1
    restart: unless-stopped

  master:
    image: docker.osgeo.org/geoserver:2.27.3
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver_data:/opt/geoserver_data
    environment:
      - GEOSERVER_ADMIN_PASSWORD=secret
    deploy:
      replicas: 1
    restart: no

  geoserver:
    image: docker.osgeo.org/geoserver:2.27.3
    volumes:
      - ./geoserver_data:/opt/geoserver_data:ro
    deploy:
      replicas: 0
    restart: unless-stopped